### ISSUE TITLE
Object location on canvas is not same as user setting location

### ISSUE THREAD

**Issue by rlaebqebq** [layerhub-io/layerhub-io#24]
for example, I want to move 'specialId' object to {left: 0, top: 0} on Canvas
so i tried this. `editor.objects.update({ left: 0, top: 0 }, 'specialId')`
but object move wrong position

When I add object { left: 0, top: 0 } on canvas, the object is located at (0,0) of canvas.
However, if you check the object with `console.log(editor.objects.findById('specialId'))`
left and top are not 0, but { left: -600.5, top: -208 }

so if i want to move object to {left: 0, top: 0} on Canvas,
i have to write this .`editor.objects.update({ left: -600.5, top: -208 }, 'specialId')`

I wonder how to calculate and estimate the real left, top value.

same issue
https://github.com/fabricjs/fabric.js/issues/4206

**Comment by chloe-bm** [comment]
@rlaebqebq fixed on  `"@layerhub-io/react": ^0.3.3`
