### ISSUE TITLE
Getting error in vercel

### ISSUE THREAD

**Issue by jsonpreet** [layerhub-io/layerhub-io#25]
Trying to deploy project on Vercel but I am getting error related to canvas package
![image](https://user-images.githubusercontent.com/26606638/194600772-ab0a9bc3-4eee-4bfb-b7c3-80aab16b80f3.png)

**Comment by chloe-bm** [comment]
@jsonpreet this project should not be deployable. If you are to deploy the editor, please use this version: https://github.com/layerhub-io/react-design-editor

**Comment by jsonpreet** [comment]
Sorry I deployed this: https://github.com/layerhub-io/react-design-editor

**Comment by chloe-bm** [comment]
Create issue in that repo please.

**Comment by resumaniamalay** [comment]
https://github.com/layerhub-io/react-design-editor is not found

> @jsonpreet this project should not be deployable. If you are to deploy the editor, please use this version: https://github.com/layerhub-io/react-design-editor
